### 

POST http://localhost:5000/order HTTP/1.1
Content-Type: application/json

{
  "product_name": "product3",
  "description": "description3",
  "price": 5000.0,
  "event_timestamp": "2024-07-09T11:42:00"
}